### PR TITLE
Fix registryIdRef

### LINKED ISSUE #4: registryIdRef not working in Replication resource
Hi All

Testing the Replication resource using the registryIdRef showed that the reference to a Registry object seems not to work. 

image

Looking at the code I suspect the issue is that the referencing code is not fetching the right property from the referenced object. 

In https://github.com/globallogicuki/provider-harbor/blob/main/config/replication/config.go the reference is specified but does not have a custom Extractor to reference the right parameter in the Registry object which would be "registryId", see screenshot.
image

By default, the reference fetches the "id" parameter of a referenced object.

### PR DESCRIPTION
**Pull request by tschlaepfer**
### Description of your changes
This pull request fixes the registryIdRef for Replication object by adding a custom extractor function to fetch the "registryId" parameter of a Registry object. Additionally, this pull request adds an option to the Project resource to create cache proxy projects by supplying the registryId parameter also via registryIdRef.

Fixes #4

I have:

- [X] Read and followed Crossplane's [contribution process].
- [ ] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

The provider has been tested locally as described in #4. Results from the test can also be found there.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Comment by lornest** [comment]
@tschlaepfer - just getting around to looking at this. I'm testing out locally using Kind and the manifests in `examples-gernerated/registry/replication.yaml` and still getting the error `Missing required argument: The argument "registry_id" is required, but no definition was found.` on the replication object. 

Did you have to change the manifests at all?

**Comment by tschlaepfer** [comment]
Hi Lorne No, if the new CRDs are deployed on the cluster the examples-gernerated/registry/replication.yaml example should work out of the box. Have you been able to review the registry object for status.atProvider.registryId? It may take a bit for the provider to reconcile all the objects.  Best regardsTobias   From: Lorne Stalker ***@***.***>Date: Tuesday, 30 July 2024 at 15:02To: globallogicuki/provider-harbor ***@***.***>Cc: Tobias Schlaepfer ***@***.***>, Mention ***@***.***>Subject: Re: [globallogicuki/provider-harbor] Fix registryIdRef (PR ***@***.*** - just getting around to looking at this. I'm testing out locally using Kind and the manifests in examples-gernerated/registry/replication.yaml and still getting the error Missing required argument: The argument "registry_id" is required, but no definition was found. on the replication object.Did you have to change the manifests at all?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by lornest** [comment]
Yeah, ignore me @tschlaepfer sorry! I deleted my comment because it was just me being stupid - I was still running my own version of the provider! Looks good to me, just a final few checks and I'll merge

**Comment by lornest** [comment]
Thanks for the contribution @tschlaepfer. Linting was playing up - I fixed the real lint errors (was just some go formatting), but looks like the other issue is a known issue with the golintci Github Action so I'm merging and will resolve in the main repo.

**Pull request merged**
